using System.Text;
using E3Studio.Models;

namespace E3Studio.Services.PostProcessor;

/// <summary>
/// Base class for all post-processors
/// </summary>
public abstract class PostProcessorBase
{
    public abstract string Name { get; }
    public abstract string Description { get; }
    public abstract string FileExtension { get; }
    
    // Machine capabilities
    public virtual bool SupportsArcs => true;
    public virtual bool SupportsCannedCycles => true;
    public virtual bool SupportsToolChange => true;
    public virtual bool SupportsSubprograms => false;
    public virtual int MaxLineNumber => 99999;
    public virtual int LineNumberIncrement => 10;
    
    // Format settings
    public virtual string DecimalFormat => "F3";
    public virtual string FeedFormat => "F0";
    public virtual bool UseLineNumbers => false;
    public virtual string CommentStart => "(";
    public virtual string CommentEnd => ")";
    public virtual string BlockDelete => "/";
    
    // Current state
    protected double CurrentX { get; set; }
    protected double CurrentY { get; set; }
    protected double CurrentZ { get; set; }
    protected double CurrentF { get; set; }
    protected int CurrentS { get; set; }
    protected int CurrentTool { get; set; }
    protected int LineNumber { get; set; }
    
    /// <summary>
    /// Generate G-Code for all toolpaths
    /// </summary>
    public virtual string Generate(Project project, List<Toolpath> toolpaths)
    {
        var sb = new StringBuilder();
        LineNumber = 10;
        
        GenerateHeader(sb, project, toolpaths);
        GenerateSetup(sb);
        
        foreach (var toolpath in toolpaths.Where(t => t.IsEnabled))
        {
            GenerateToolpath(sb, toolpath, project.Stock);
        }
        
        GenerateFooter(sb);
        
        return sb.ToString();
    }
    
    /// <summary>
    /// Generate G-Code with explicit stock, tools and options
    /// </summary>
    public virtual string Generate(List<Toolpath> toolpaths, Stock stock, List<Tool> tools, PostProcessorOptions options)
    {
        var sb = new StringBuilder();
        LineNumber = 10;
        
        // Apply options (these are virtual properties in derived classes)
        var decimalFormat = $"F{options.DecimalPlaces}";
        var useLineNumbers = options.IncludeLineNumbers;
        
        // Generate header manually
        sb.AppendLine($"{CommentStart} Generated by E3Studio {CommentEnd}");
        sb.AppendLine($"{CommentStart} Stock: {stock.Width} x {stock.Height} x {stock.Thickness} {CommentEnd}");
        sb.AppendLine();
        
        // Setup
        sb.AppendLine(options.UseMetric ? "G21" : "G20"); // Units
        sb.AppendLine("G90"); // Absolute positioning
        sb.AppendLine($"G54"); // Work offset
        
        // Process each toolpath
        foreach (var toolpath in toolpaths.Where(t => t.IsEnabled))
        {
            GenerateToolpath(sb, toolpath, stock);
        }
        
        // Footer
        sb.AppendLine("M5"); // Spindle off
        sb.AppendLine("M9"); // Coolant off  
        sb.AppendLine($"G0 Z{options.SafeHeight:F2}"); // Raise to safe height
        sb.AppendLine("M30"); // Program end
        
        return sb.ToString();
    }
    
    protected abstract void GenerateHeader(StringBuilder sb, Project project, List<Toolpath> toolpaths);
    protected abstract void GenerateSetup(StringBuilder sb);
    protected abstract void GenerateToolpath(StringBuilder sb, Toolpath toolpath, Stock stock);
    protected abstract void GenerateFooter(StringBuilder sb);
    
    // Helper methods
    protected string F(double value) => value.ToString(DecimalFormat, System.Globalization.CultureInfo.InvariantCulture);
    protected string Feed(double value) => value.ToString(FeedFormat, System.Globalization.CultureInfo.InvariantCulture);
    
    protected string Line(string code)
    {
        if (UseLineNumbers)
        {
            var result = $"N{LineNumber} {code}";
            LineNumber += LineNumberIncrement;
            return result;
        }
        return code;
    }
    
    protected string Comment(string text) => $"{CommentStart}{text}{CommentEnd}";
    
    protected void Rapid(StringBuilder sb, double? x = null, double? y = null, double? z = null)
    {
        var parts = new List<string> { "G0" };
        if (x.HasValue) { parts.Add($"X{F(x.Value)}"); CurrentX = x.Value; }
        if (y.HasValue) { parts.Add($"Y{F(y.Value)}"); CurrentY = y.Value; }
        if (z.HasValue) { parts.Add($"Z{F(z.Value)}"); CurrentZ = z.Value; }
        sb.AppendLine(Line(string.Join(" ", parts)));
    }
    
    protected void Linear(StringBuilder sb, double? x = null, double? y = null, double? z = null, double? f = null)
    {
        var parts = new List<string> { "G1" };
        if (x.HasValue) { parts.Add($"X{F(x.Value)}"); CurrentX = x.Value; }
        if (y.HasValue) { parts.Add($"Y{F(y.Value)}"); CurrentY = y.Value; }
        if (z.HasValue) { parts.Add($"Z{F(z.Value)}"); CurrentZ = z.Value; }
        if (f.HasValue && Math.Abs(f.Value - CurrentF) > 0.01) { parts.Add($"F{Feed(f.Value)}"); CurrentF = f.Value; }
        sb.AppendLine(Line(string.Join(" ", parts)));
    }
    
    protected void Arc(StringBuilder sb, bool clockwise, double x, double y, double i, double j, double? f = null)
    {
        if (!SupportsArcs)
        {
            // Linearize arc if not supported
            LinearizeArc(sb, clockwise, x, y, i, j, f);
            return;
        }
        
        var code = clockwise ? "G2" : "G3";
        var parts = new List<string> { code, $"X{F(x)}", $"Y{F(y)}", $"I{F(i)}", $"J{F(j)}" };
        if (f.HasValue && Math.Abs(f.Value - CurrentF) > 0.01) { parts.Add($"F{Feed(f.Value)}"); CurrentF = f.Value; }
        sb.AppendLine(Line(string.Join(" ", parts)));
        CurrentX = x;
        CurrentY = y;
    }
    
    private void LinearizeArc(StringBuilder sb, bool clockwise, double endX, double endY, double i, double j, double? f, int segments = 36)
    {
        double cx = CurrentX + i;
        double cy = CurrentY + j;
        double startAngle = Math.Atan2(CurrentY - cy, CurrentX - cx);
        double endAngle = Math.Atan2(endY - cy, endX - cx);
        double radius = Math.Sqrt(i * i + j * j);
        
        if (clockwise)
        {
            if (endAngle >= startAngle) endAngle -= 2 * Math.PI;
        }
        else
        {
            if (endAngle <= startAngle) endAngle += 2 * Math.PI;
        }
        
        double angleSpan = endAngle - startAngle;
        int numSegments = Math.Max(4, (int)(Math.Abs(angleSpan) / (2 * Math.PI) * segments));
        
        for (int seg = 1; seg <= numSegments; seg++)
        {
            double t = (double)seg / numSegments;
            double angle = startAngle + angleSpan * t;
            double x = cx + radius * Math.Cos(angle);
            double y = cy + radius * Math.Sin(angle);
            Linear(sb, x, y, f: f);
        }
    }
    
    protected void SpindleOn(StringBuilder sb, int rpm, bool clockwise = true)
    {
        CurrentS = rpm;
        sb.AppendLine(Line($"{(clockwise ? "M3" : "M4")} S{rpm}"));
    }
    
    protected void SpindleOff(StringBuilder sb)
    {
        sb.AppendLine(Line("M5"));
    }
    
    protected void CoolantOn(StringBuilder sb, bool flood = true)
    {
        sb.AppendLine(Line(flood ? "M8" : "M7"));
    }
    
    protected void CoolantOff(StringBuilder sb)
    {
        sb.AppendLine(Line("M9"));
    }
    
    protected void ToolChange(StringBuilder sb, int toolNumber, string? toolName = null)
    {
        if (!SupportsToolChange) return;
        CurrentTool = toolNumber;
        if (toolName != null) sb.AppendLine(Comment($"Tool: {toolName}"));
        sb.AppendLine(Line($"M6 T{toolNumber}"));
    }
    
    protected void Dwell(StringBuilder sb, double seconds)
    {
        sb.AppendLine(Line($"G4 P{F(seconds)}"));
    }
    
    protected void ProgramEnd(StringBuilder sb)
    {
        sb.AppendLine(Line("M30"));
    }
}

/// <summary>
/// Post-processor factory
/// </summary>
public static class PostProcessorFactory
{
    private static readonly Dictionary<string, Func<PostProcessorBase>> _processors = new()
    {
        { "Generic", () => new GenericPostProcessor() },
        { "GRBL", () => new GrblPostProcessor() },
        { "Mach3", () => new Mach3PostProcessor() },
        { "Mach4", () => new Mach4PostProcessor() },
        { "LinuxCNC", () => new LinuxCNCPostProcessor() },
        { "HAAS", () => new HaasPostProcessor() },
        { "Mazak", () => new MazakPostProcessor() },
        { "Fanuc", () => new FanucPostProcessor() }
    };
    
    public static IEnumerable<string> AvailableProcessors => _processors.Keys;
    
    public static PostProcessorBase Create(string name)
    {
        if (_processors.TryGetValue(name, out var factory))
            return factory();
        return new GenericPostProcessor();
    }
}
